class Cell {
  constructor(r, g, b) {
    this.r = r
    this.g = g
    this.b = b
  }
}

function diamondSquare(DATA_SIZE, smoothness) {

  // Create an empty grid
	var data = new Array(DATA_SIZE);
	for (var i = 0; i < DATA_SIZE; i++) {
		data[i] = new Array(DATA_SIZE);

    for (var j = 0; j < DATA_SIZE; j++) {
      data[i][j] = 0;
    }
	}

	// Seed the data
  var SEED = 128.0;
	data[0][0] = data[0][DATA_SIZE - 1] = data[DATA_SIZE - 1][0] = data[DATA_SIZE -1][DATA_SIZE - 1] = SEED;

  // This iterates the algorithm (based on smoothness), increasing the "depth"
	for (var sideLength = DATA_SIZE - 1; sideLength >= 2; sideLength /= 2, smoothness /= 2.0) {
		var halfSide = sideLength / 2;

    // SQUARE
		for (var x = 0; x < DATA_SIZE - 1; x += sideLength) {
		    for (var y = 0; y < DATA_SIZE - 1; y += sideLength) {

            // Get the average of the four surrounding corners
		        var avg = data[x][y] +
                data[x + sideLength][y] +
                data[x][y + sideLength] +
                data[x + sideLength][y + sideLength];
		        avg /= 4.0;

            // Set the square value to the average + a random number affected by the smoothness
		        data[x + halfSide][y + halfSide] = avg + (Math.random() * 2 * smoothness) - smoothness;
		    }
		}

    // DIAMOND
		for (var x = 0; x < DATA_SIZE - 1; x += halfSide) {
		    for (var y = (x + halfSide) % sideLength; y < DATA_SIZE - 1; y += sideLength) {

            // Get the average of the four points on the diamond
		        var avg =
                    data[(x - halfSide + DATA_SIZE - 1) % (DATA_SIZE - 1)][y] +
                    data[(x + halfSide) % (DATA_SIZE - 1)][y] +
                    data[x][(y + halfSide) % (DATA_SIZE - 1)] +
                    data[x][(y - halfSide + DATA_SIZE - 1) % (DATA_SIZE - 1)];
		        avg /= 4.0;

		        avg = avg + (Math.random() * 2 * smoothness) - smoothness;
		        data[x][y] = avg;

            // Wrap the values
		        if (x == 0) data[DATA_SIZE - 1][y] = avg;
		        if (y == 0) data[x][DATA_SIZE - 1] = avg;
		    }
		}
	}

	return data;
}

function getGrid(size, smoothness) {
  var grid = new Array(size)
  var data = diamondSquare(size, smoothness)

  for (var x = 0; x < size; x++) {
    grid[x] = new Array(size)

    for (var y = 0; y < size; y++) {
      var colour = []

      // Map the noise values generated by the Diamond-Square algorithm to rgb colours
      var DSvalue = data[x][y]
      if (DSvalue < 70) {
	      // Deep ocean (lowest)
        colour = [31, 3, 168]
      } else if (DSvalue < 100 && DSvalue >= 70) {
	      // Shallow ocean
        colour = [15, 144, 199]
      } else if (DSvalue < 120 && DSvalue >= 100) {
	      // Beach?
        colour = [217, 219, 141]
      } else if (DSvalue < 150 && DSvalue >= 120) {
	      // Grassland / meadow?
        colour = [99, 196, 0]
      } else if (DSvalue < 180 && DSvalue >= 150) {
	      // Forest?
        colour = [0, 127, 20]
      } else if (DSvalue < 210 && DSvalue >= 180) {
	      // Hills/rocky area
        colour = [100, 82, 29]
      } else {
	      // Mountain-y area? (highest)
        colour = [100, 83, 64]
      }

      grid[x][y] = new Cell(colour[0], colour[1], colour[2])
    }
  }

  return grid
}
